language: node_js
node_js:
  - node
branches:
  only:
    - develop
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: deploy.sh
  on:
    branch: develop
addons:
  apt:
    packages:
      - ncftp
